apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: vote
spec:
  selector:
    matchLabels:
      app: voteapp
  template:
    metadata:
      labels:
        app: voteapp
    spec:
      containers:
      - name: votingapp
        image: kodekloud/examplevotingapp_vote:before
        ports:
        - containerPort: 80
