apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels:
    name: gop
spec:
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc
  containers:
    - name: gop-fileserver
      image: kodekloud/fileserver
      volumeMounts:
        - name: data-store
          mountPath: /web
      ports:
        - containerPort: 8080
